export const InitializationResultValue = {
  OK: 0,
} as const;

export const SettingsValue = {
  PRECISION_MODE_RELAXED: 1,
  OPERATING_MODE_MEASURE: 1,
  MEASUREMENT_PRESET_THIRTY_SECONDS_ALL_METRICS: 9,
  CAMERA_MODE_OFF: 0,
  CAMERA_MODE_FACING_USER: 1,
  ONBOARDING_MODE_HIDDEN: 0,
  UI_VERSION_V2: 1,
} as const;

export const MeasurementStateValue = {
  NOT_STARTED: 0,
  WAITING_FOR_FACE: 1,
  RUNNING_SIGNAL_SHORT: 2,
  RUNNING_SIGNAL_GOOD: 3,
  RUNNING_SIGNAL_BAD: 4,
  RUNNING_SIGNAL_BAD_DEVICE_UNSTABLE: 5,
  FINALIZING: 6,
  FINISHED: 7,
  FAILED: 8,
} as const;

export const EnvironmentConditionValue = {
  FACE_POSITION: 0,
  FOREHEAD_VISIBLE: 1,
  GLASSES_NOT_DETECTED: 2,
  SUFFICIENT_LIGHT_LEVEL: 3,
  EVEN_LIGHTING: 4,
  NO_BACKLIGHT: 5,
  FACE_STABLE: 6,
  DEVICE_STABLE: 7,
} as const;

export const RiskFactorValue = {
  GENDER_MALE: 0,
  GENDER_FEMALE: 1,
  GENDER_OTHER: 2,
  PHYSICAL_ACTIVITY_SEDENTARY: 0,
  PHYSICAL_ACTIVITY_LIGHTLY_ACTIVE: 1,
  PHYSICAL_ACTIVITY_MODERATELY: 2,
  PHYSICAL_ACTIVITY_VERY_ACTIVE: 3,
  PHYSICAL_ACTIVITY_EXTRA_ACTIVE: 4,
  RACE_WHITE: 0,
  RACE_AFRICAN_AMERICAN: 1,
  RACE_OTHER: 2,
  HYPERTENSION_TREATMENT_NOT_NEEDED: 0,
  HYPERTENSION_TREATMENT_NO: 1,
  HYPERTENSION_TREATMENT_YES: 2,
  FAMILY_HISTORY_NONE: 0,
  FAMILY_HISTORY_NONE_FIRST_DEGREE: 1,
  FAMILY_HISTORY_FIRST_DEGREE: 2,
  PARENTAL_HISTORY_NONE: 0,
  PARENTAL_HISTORY_ONE: 1,
  PARENTAL_HISTORY_BOTH: 2,
} as const;

export const CAMERA_VIEW_SIZE = 300;
export const CAMERA_PREVIEW_HEIGHT = CAMERA_VIEW_SIZE * (16 / 9);
export const CAMERA_PREVIEW_TOP =
  -(CAMERA_PREVIEW_HEIGHT - CAMERA_VIEW_SIZE) / 2;
